name: Prueba num 1

on:
  push:
    branches:
      - master

jobs:
  decir-hola:
    runs-on: ubuntu-latest

    steps:
    - name: Mostrar mensaje
      run: echo "Hola Checos"
    - name: Enviar peticion
      run: curl -X POST 'https://webhook.site/892f2749-aba3-44c8-af63-04640edf7a85' -H 'content-type: application/json' -d $'{"nombre": "Maicol"}'